CREATE TABLE USUARIO (
	userId SERIAL,
	nombreUsuario VARCHAR(30) NOT NULL,
	contrasena VARCHAR(30) NOT NULL,
	privilegios VARCHAR(30) NOT NULL,
	nombre VARCHAR(30) NOT NULL,
	SSId INT NOT NULL,
	email VARCHAR(50) NOT NULL,
	numTelefono INT NOT NULL,
	
	PRIMARY KEY (userId)
);

CREATE TABLE CONTABILIDAD (
	operacionId SERIAL,
	userId INT REFERENCES USUARIO(userId),
	fechaInicio DATE NOT NULL,
	fechaFin DATE NOT NULL,
	ingresos INT NOT NULL,
	gastos INT NOT NULL,
	balance INT NOT NULL,
	
	PRIMARY KEY (operacionId)
);

CREATE TABLE DISTRIBUIDOR(
	distribId VARCHAR(9) NOT NULL,
	nombreDist VARCHAR(30) NOT NULL,
	emailDist VARCHAR(50) NOT NULL,
	distTelf INT NOT NULL,
	
	PRIMARY KEY (distribId)
);

CREATE TABLE PEDIDO(
	pedidoId SERIAL,
	userId INT REFERENCES USUARIO(userId),
	fecha DATE NOT NULL,
	precioTotal DECIMAL(7, 2) NOT NULL,
	distribId VARCHAR(9) REFERENCES DISTRIBUIDOR(distribId),
		
	PRIMARY KEY (pedidoId)
);

CREATE TABLE PRODUCTO(
	nombreProd VARCHAR(30) NOT NULL,
	distribId VARCHAR(9) REFERENCES DISTRIBUIDOR(distribId),
	tipo VARCHAR(30) NOT NULL,
	cantidad INT,
	costeUnitario DECIMAL(5, 2) NOT NULL,
		
	PRIMARY KEY (nombreProd)
);