/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Connection;
import javax.swing.*;
import modelo.db.Conexion;
import modelo.db.OperacionesBD_distribuidor;
import modelo.db.OperacionesBD_producto;
import modelo.db.OperacionesBD_usuario;
import modelo.entidad.*;
import javax.swing.table.DefaultTableModel;

public class VentanaPrincipal extends JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setPreferredSize(new Dimension(400, 300));
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new JLabel();
        log = new JPanel();
        pass = new JPasswordField();
        acceder = new JButton();
        passLabel = new JLabel();
        user = new JTextField();
        userLabel = new JLabel();
        menu = new JPanel();
        jButton1 = new JButton();
        distButton = new JButton();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jButton5 = new JButton();
        distPanel = new JPanel();
        distTable = new JTable();
        addDist = new JButton();
        grid = new GridBagConstraints();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("StockManager");
        setBackground(new java.awt.Color(3, 132, 186));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        log.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        log.setLayout(new java.awt.GridBagLayout());

        pass.setPreferredSize(new java.awt.Dimension(100, 22));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        log.add(pass, gridBagConstraints);

        acceder.setText("Acceder");
        acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        log.add(acceder, gridBagConstraints);
        

        passLabel.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        log.add(passLabel, gridBagConstraints);

        user.setPreferredSize(new java.awt.Dimension(100, 22));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        log.add(user, gridBagConstraints);

        userLabel.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        log.add(userLabel, gridBagConstraints);

        getContentPane().add(log, java.awt.BorderLayout.CENTER);

        jButton1.setText("Productos");

        distButton.setText("Distribuidores");
        distButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Usuarios");

        jButton4.setText("Ver pedidos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Hacer pedido");

        GroupLayout menuLayout = new GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(menuLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(menuLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addComponent(distButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton5))
                .addGap(26, 26, 26)
                .addComponent(jButton4)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(distButton, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(menuLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        menu.setPreferredSize(new Dimension(400, 300));
        menu.setVisible(false);
        getContentPane().add(menu, java.awt.BorderLayout.PAGE_START);
        
        distPanel.setBorder(BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        distPanel.setLayout(new GridBagLayout()); // Asegúrate de que distPanel tenga un layout
        GridBagConstraints grid = new GridBagConstraints();
        distTable.setPreferredSize(new Dimension(300, 200));
        JScrollPane scrollPane = new JScrollPane(distTable); // Agrega distTable a un JScrollPane
        distPanel.add(scrollPane, grid); // Agrega el JScrollPane a distPanel
        model = new DefaultTableModel();
        addDist.setText("Añadir distribuidor");
        addDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDistActionPerformed(evt);
            }
        });
        grid.gridy = 1;
        distPanel.add(addDist, grid);
        distPanel.setVisible(false);



        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederActionPerformed
        
        if(user.getText().isEmpty() || pass.getPassword().length == 0){
            JOptionPane.showMessageDialog(null, "Rellena los campos para continuar", "Error de acceso", JOptionPane.ERROR_MESSAGE);
        }else{
            String usuario = user.getText();
            char[] contra = pass.getPassword();
            if(OperacionesBD_usuario.getUsuario_BD(usuario) != null){
                Usuario usuarioBD = OperacionesBD_usuario.getUsuario_BD(usuario);
                if(usuarioBD.getPass().equals(String.valueOf(contra))){
                    menu.setVisible(true);
                    log.setVisible(false);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Error de acceso", JOptionPane.ERROR_MESSAGE);
                }

            }else{
                JOptionPane.showMessageDialog(null, "El usuario no es correcto", "Error de acceso", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_accederActionPerformed
    private void addDistActionPerformed(java.awt.event.ActionEvent evt){
        JPanel ingresaDist = new JPanel();
        ingresaDist.setLayout(new BoxLayout(ingresaDist, BoxLayout.Y_AXIS)); // Establecer el layout a BoxLayout
        ingresaDist.setPreferredSize(new Dimension(300, 200)); // Establecer el tamaño preferido del panel
        JTextField id = new JTextField();
        JTextField nombre = new JTextField();
        JTextField mail = new JTextField();
        JTextField tlfn = new JTextField();
        ingresaDist.add(new JLabel("NIF:"));
        ingresaDist.add(id);
        ingresaDist.add(new JLabel("Nombre:"));
        ingresaDist.add(nombre);
        ingresaDist.add(new JLabel("Email:"));
        ingresaDist.add(mail);
        ingresaDist.add(new JLabel("Teléfono:"));
        ingresaDist.add(tlfn);
        int result = JOptionPane.showConfirmDialog(null, ingresaDist, "Añadir distribuidor", JOptionPane.OK_CANCEL_OPTION);
        if(result == JOptionPane.OK_OPTION){
            Distribuidor distribuidor = new Distribuidor(id.getText(), nombre.getText(), mail.getText(), Integer.parseInt(tlfn.getText()));
            OperacionesBD_distribuidor.addDistrib_BD(distribuidor);
            model.addRow(new Object[]{distribuidor.getId(), distribuidor.getNombre(), distribuidor.getMail(), distribuidor.getTlfn()});
        }
    }
    private void distButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Distribuidor[] distribuidores = OperacionesBD_distribuidor.getListaDistribuidores_BD();
        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Email");
        model.addColumn("Teléfono");
        for(int i = 0; i < distribuidores.length; i++){
            model.addRow(new Object[]{distribuidores[i].getId(), distribuidores[i].getNombre(), distribuidores[i].getMail(), distribuidores[i].getTlfn()});
        }
        distTable.setModel(model);
        menu.setVisible(false);
        distPanel.setVisible(true);
        add(distPanel);
    }                                          

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });

        
        //**PRESCINDIBLE** para depuración - app se conecta a la BD correctamente al iniciar
        Connection con = Conexion.getConexion();
        //Desconexión de la BD
        Conexion.closeConexion(con);

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton acceder;
    private JButton jButton1;
    private JButton distButton;
    private JButton jButton3;
    private JButton jButton4;
    private JButton jButton5;
    private JButton addDist;
    private JLabel jLabel1;
    private JPanel log;
    private JPanel menu;
    private JPanel distPanel;
    private JTable distTable;
    private JPasswordField pass;
    private JLabel passLabel;
    private JTextField user;
    private JLabel userLabel;
    private DefaultTableModel model;
    private GridBagConstraints grid;
    // End of variables declaration//GEN-END:variables
}
